### ISSUE TITLE
api.render.RenderCreature Crash

### ISSUE THREAD

**Issue by xKillerbees** [Lycanite/LycanitesMobs#129] opened 2015-12-05 04:48 UTC
http://pastebin.com/v2Vw0Xh8

Walking around on a server crash.

**Comment by Lycanite** [comment] 2015-12-07 09:12
Hmm so it looks like there was a crash when a Lobber was rendering, does this happen every time?

I'll do some tests but an if there is an issue then it's extremely rare as this rendering code has been like this for a very long time, other mods can sometimes not finish rendering something properly which can then break rendering for something else, so it could also be a problem caused by another mod.

If you get another crash that mentions the tesselator but it leads up to another mod or vanilla render, then there is definitely a mod that's breaking the rendering of everything else.

I'll run some tests in the mean time though!

**Comment by Lycanite** [comment] 2016-05-18 12:17
This is most likely caused by another mod not closing the tessellator causing a crash when something else (in this case a Lobber) starts to use it, in 1.9 things have bee improved to essentially stop issues like this from happening by mistake.

**Closed by Lycanite** 2016-05-18 12:17 UTC
