### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by CrystalNole** [Lycanite/LycanitesMobs#202] opened 2017-01-21 04:24 UTC
I am currently running a private server for some friends and I installed Lycanites. Occasionally for seemingly no reason. It's about twenty plus lines of this spamming my console and lagging almost everyone out and locking the server for a bit. 

The code is: [lycanite.lycanitesmobs.core.spawning.SpawnTypeBase:spawnMobs:516]: java.lang.NullPointerException

**Comment by xlxAciDxlx** [comment] 2017-01-21 17:15
Duplicate of #191

**Comment by xlxAciDxlx** [comment] 2017-01-21 17:16
Sorry, #196 and can't edit my comment on mobile lol

**Closed** 2017-08-07 10:08 UTC
