### ISSUE TITLE
1.9 ALPHA has a big memory leak

### ISSUE THREAD

**Issue by ArMoReDfUrY** [Lycanite/LycanitesMobs#145] opened 2016-05-07 15:45 UTC
SSP used all 4gigs of ram in less than 15 minutes.
might be related to the vanilla memory leak in entity code but i don't think this is the case.

**Comment by Lycanite** [comment] 2016-05-07 16:03
I'll leave a game running to see if I can find this issue, so far I can't really see any memory leak, though they can be tricky to find.

**Comment by ArMoReDfUrY** [comment] 2016-05-08 03:45
hmm. it's probably a conflict with one of the other mods. i'll try to isolate which is causing it.
might take a day or so.

**Comment by JCMais** [comment] 2016-05-11 01:23
@Lycanite  I think this was show on jonbams stream early today, wasn't it? Or did him found the mod causing it? (I stopped watching before he fixed the issue)

**Comment by Lycanite** [comment] 2016-05-11 06:54
I'm not too sure @JCMais, I've got a build of JonBams pack and I can't replicate the problem at all, I even tried the same forge version as him but my the pack ran great for me. I'm going to keep looking into this as I'm slowly working on a pack of my own as well which is loaded up with heavy shader mods which will push rendering.

If there is an issue it could be related to entity AI as there is a pathing memory leak that has been in Minecraft for a long time which is finally fixed in 1.9.3 so hopefully those fixes are either ported to forge for 1.9.0 or forge for 1.9.3/4 which show up soon.

I'll keep testing but so far I can't get the leak to happen for me, I'll try on my older PC to see if lower specs could be the cause due to not finishing something quick enough or what not.

**Comment by ArMoReDfUrY** [comment] 2016-05-12 14:22
Ok i've been testing and updating and i think there is possibly an issue with Evilcraft... however after going through all the entity mods and a few one on one tests it seams to be fairly random when this leak kicks in whilst running with evilcraft. 
its possible that having a ton of entity mods might be causing some niche conflicts during worldgen.
maybe the vanilla leak too?

anyway it seams stable enough now with the updates, thanks on that by the way :+1: 
unless you find a link to evilcraft being the culprit i'd close this and blame vanilla ;)

**Comment by Lycanite** [comment] 2016-05-12 14:24
I'm not too certain, but too many entity mods shouldn't cause a problem, the spawns don't work harder when there's more entities to spawn, instead they randomly pick from a larger list which doesn't affect performance.

There is a known memory that has been in vanilla for a long time (since before 1.8) which has been fixed in 1.9.3+ so hopefully when forge moves to 1.9.4 we'll get this fix.

**Comment by Lycanite** [comment] 2016-05-18 12:07
I'm gonna close this issue as I can't pin point anything, if this issue reoccurs whip up a new git issue and I'll look into it.

**Closed by Lycanite** 2016-05-18 12:07 UTC
