### ISSUE TITLE
Client Side Crash

### ISSUE THREAD

**Issue by DPxKnightxZero** [Lycanite/LycanitesMobs#123] opened 2015-11-05 06:52 UTC
https://gist.github.com/DPxKnightxZero/88411a9d3d1a964cb139

**Comment by Lycanite** [comment] 2016-05-18 12:25
This was a crash caused by player names that end with an 's' due to how pet names are displayed such as "Lycanite's Grue" being the usual case but "James' Grue" in the case where a name ends in an s and the apostrophe has to be on the end of the name instead. This is now fixed.

**Closed by Lycanite** 2016-05-18 12:25 UTC
