### ISSUE TITLE
[Pets] Soulstone Broken On Servers

### ISSUE THREAD

**Issue by JangoFe** [Lycanite/LycanitesMobs#304] opened 2018-01-12 03:41 UTC
When i use soulstone on the tamed by myself creature nothing happen. Stone just disappear and creature not bind to me.

**Comment by Lycanite** [comment] 2018-01-15 08:17
I'll run some tests on this, thanks for the bug report.

**Comment by Lycanite** [comment] 2018-01-15 17:03
I can't replicate this, is this in the latest 1.17.5.1 build for 1.12.X and single player or on a server?

**Comment by Lycanite** [comment] 2018-01-18 08:22
Oops just noticed it says multiplayer in the title! I'll run some dedicated server and open to lan tests.

**Comment by Lycanite** [comment] 2018-01-24 09:22
This is probably caused by this: https://github.com/Lycanite/LycanitesMobs/issues/310
So I'll be closing this issue as the Soulstone itself is working fine, but some mobs aren't recognising their owner and are thus ignoring Soulstones.

**Closed by Lycanite** 2018-01-24 09:22 UTC
Labels: question
