### ISSUE TITLE
Dim Light Level Should Be 7 Down Not 8

### ISSUE THREAD

**Issue by stats** [Lycanite/LycanitesMobs#56] opened 2015-03-03 00:22 UTC
EntityCreatureBase.java has a light level check ( public byte testLightLevel(int x, int y, int z) at line 2635)  that tests for a light level <= 8. This equates to a "dim" light level, which would allow hostile mobs to spawn.

This is different than the rules for typical minecraft spawning which would use <= 7 for mobs to spawn in the overworld and also different from NEI's mob spawn overlay which checks for a light level >= 8 to show where a mob can **not** spawn.

Is this by design?

**Comment by Lycanite** [comment] 2015-03-03 08:59
Oh nice find, looks like that was intended to be < 8, I'll change it to <= 7 though as that is more clear! Nice find!

**Comment by stats** [comment] 2015-03-03 10:58
Thanks! I appreciate all the work you do, you make MC more fun!

**Comment by Lycanite** [comment] 2015-03-03 18:37
Fixed in an upcoming update.

**Closed by Lycanite** 2015-03-03 18:37 UTC
Labels: bug
