### ISSUE TITLE
[1.12.2] Cascading Worldgen

### ISSUE THREAD

**Issue by Zsashas** [Lycanite/LycanitesMobs#281] opened 2017-12-19 00:50 UTC
[16:48:19] [Server thread/WARN] [FML]: Lycanites Mobs loaded a new chunk (99, 46  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

**Comment by Lycanite** [comment] 2017-12-19 10:56
Is this with any special settings or just random? It is likely caused by the Ooze/Pure Lava lakes which should avoid that but it looks like there's a small chance that they bleed over into another chunk. Was this message repeated a lot or just once?

**Comment by Zsashas** [comment] 2017-12-19 11:21
Only a couple of times. Not nearly as often as, say, Natura or Roguelike Dungeons.

**Comment by Lycanite** [comment] 2017-12-19 11:44
Ah, there's a small random chance so I'll take a look into it, but the one off wont be too bad for the mean time, it basically means that when an Ooze/Pure Lava lake is generated, it goes over into the next chunk and forces that chunk to generate, if it happens a lot this can cause a knock on effect where it keeps generating chunk after chunk, but the rare one off wont cause any issues.

**Comment by Adaptivity** [comment] 2017-12-28 06:34
@Lycanite https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/ heres reddit thread about this and solution to fix it.

**Comment by Lycanite** [comment] 2017-12-28 07:55
Ahhh I didn't know that +X, +Z and +XZ are always loaded first, so all I need to do it generate around the center of the 4 chunks instead of the center of the generated chunk. Thanks for the link will apply this fix asap.

**Comment by Lycanite** [comment] 2018-01-04 00:44
Will be fixed in 1.17.4.3. It was already at X +8, Z +8 but I think the later was sometimes in a rare case just 1 block too big. It is now X +16, Z +16 so that it is in the center of 2x2 loaded chunks which should reduce the chance of this happening to 0.

**Closed by Lycanite** 2018-01-04 00:44 UTC
Labels: bug, enhancement

**Comment by Morpheus1101** [comment] 2018-02-23 00:40
[2018-02-23 10:18:18] [Server thread/WARN]: [FML]: Lycanites Mobs loaded a new chunk (11, -5 Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

Lycanites  v1.19.1.2

**Comment by Lycanite** [comment] 2018-02-26 08:39
Try with a later build, I've very recently fixed a bug with the waterchunk spawner that was causing this.
