### ISSUE TITLE
[Pets] Flying Mounts Randomly Uncontrollable

### ISSUE THREAD

**Issue by AugiteSoul** [Lycanite/LycanitesMobs#215] opened 2017-08-10 07:35 UTC
Title says all. They move in random directions so fast that I can only control their altitude. Intended or not? (using latest 1.11.2)

**Comment by Lycanite** [comment] 2017-08-10 07:46
Nope not intended, this bug was affecting the Rocs, Raiko and Beholders but seemed to be fixed, I shall look into this thanks for the bug report!

**Comment by Lycanite** [comment] 2017-08-12 15:11
This seems to randomly happen and will require more investigation, most of the time they work as intended. I shall look further into this later.

**Comment by Lycanite** [comment] 2017-08-19 17:37
Will be fixed in the upcoming 1.17.0.0 update.

**Closed by Lycanite** 2017-08-19 17:37 UTC
Labels: bug
