### ISSUE TITLE
[Mod Compatibility] Missing Class Exception Thaumcraft Integration

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Lycanite/LycanitesMobs#413] opened 2018-05-18 08:38 UTC
Crash Report
https://gist.github.com/P3rf3ctXZer0/cee797d45c29ce841869b1f261ae12e8

**Comment by Mike-U5** [comment] 2018-05-18 08:53
Probably the issue as #411.
As a temporary fix, can downgrade to Lycanites's Mobs 1.20.2.0 or remove Thaumcraft.

**Comment by Lycanite** [comment] 2018-05-18 20:17
Ah I believe I know hat's up with this, wont take long to fix.

**Comment by Lycanite** [comment] 2018-05-18 20:18
Duplicate of #411

**Closed by Lycanite** 2018-05-18 20:18 UTC
Labels: bug
