### ISSUE TITLE
Lunar Grue causing client crashes upon new player connection to server

### ISSUE THREAD

**Issue by sharkck** [Lycanite/LycanitesMobs#191] opened 2016-11-30 20:53 UTC
I have had my client crash twice now and it appears to be because of this 'Lunar Grue' mob.  The server log shows a standard disconnect message: 
`[15:48:30] [Server thread/INFO] [journeymap/]: sharkck joining dimension 0
[15:48:30] [Netty Server IO #1/DEBUG] [FML/]: FMLHandshakeServerState: $HandshakeAck:{5}->FMLHandshakeServerState$5:DONE
[15:48:30] [Netty Server IO #1/DEBUG] [FML/]:   Next: DONE
[15:48:30] [Server thread/INFO] [chancecubes/]: No custom rewards detected for the current user!
[15:48:30] [Server thread/INFO] [EnderCore/]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[15:48:30] [Server thread/INFO] [Actually Additions/]: Sending Player Data to player sharkck with UUID 908f7355-74a7-45b9-827c-a41d920511c4.
[15:48:30] [Server thread/INFO] [Waila/]: Player EntityPlayerMP['sharkck'/247856, l='world', x=168.83, y=77.00, z=132.34] connected. Sending ping
[15:48:30] [Server thread/INFO] [Mekanism/]: Sent config to 'TextComponent{text='', siblings=[TextComponent{text='sharkck', siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg sharkck '}, hoverEvent=HoverEvent{action=SHOW_ENTITY, value='TextComponent{text='{name:"sharkck",id:"908f7355-74a7-45b9-827c-a41d920511c4"}', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}'}, insertion=sharkck}}], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=ClickEvent{action=SUGGEST_COMMAND, value='/msg sharkck '}, hoverEvent=HoverEvent{action=SHOW_ENTITY, value='TextComponent{text='{name:"sharkck",id:"908f7355-74a7-45b9-827c-a41d920511c4"}', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}'}, insertion=sharkck}}.'
[15:48:30] [Server thread/INFO] [mcjty.lib.varia.Logging/]: SMP: Player logged in: Sync diminfo to clients
[15:48:30] [Server thread/INFO] [mcjty.lib.varia.Logging/]: Sync dimension info to clients!
[15:48:30] [Server thread/INFO] [STDOUT/]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:syncDimInfoToClients:261]: dimensions.size() = 0
[15:48:30] [Server thread/INFO] [STDOUT/]: [mcjty.rftoolsdim.dimensions.RfToolsDimensionManager:syncDimInfoToClients:262]: dimensionInformation.size() = 0
[15:48:30] [Server thread/INFO] [mcjty.lib.varia.Logging/]: Send dimlet rules to the client
[15:48:30] [Server thread/INFO] [mcjty.lib.varia.Logging/]: Rules packet size: 5598 of 8192
[15:48:30] [Server thread/DEBUG] [vampirism/]: [EventHandler]Sending configuration to client (EntityPlayerMP['sharkck'/247856, l='world', x=168.83, y=77.00, z=132.34])
[15:48:30] [Server thread/INFO] [STDOUT/]: [mcjty.lib.preferences.PreferencesProperties:syncToClient:31]: syncToClient: style = STYLE_FLAT_GRADIENT
[15:48:30] [Server thread/INFO] [STDOUT/]: [lycanite.lycanitesmobs.LycanitesMobs:printInfo:400]: [LycanitesMobs] [Info] Online donations file read successfully.
[15:49:04] [Netty Server IO #1/ERROR] [FML/]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_111]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_111]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_111]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_111]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_111]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446) ~[UnpooledUnsafeDirectByteBuf.class:?]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[AbstractByteBuf.class:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) ~[NioSocketChannel.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) [AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]`

Attached are the client logfiles.  The client crashes during login before you can do anything.

[crash-2016-11-29_21.04.53-client.txt](https://github.com/Lycanite/LycanitesMobs/files/622949/crash-2016-11-29_21.04.53-client.txt)
[crash-2016-11-30_15.48.59-client.txt](https://github.com/Lycanite/LycanitesMobs/files/622950/crash-2016-11-30_15.48.59-client.txt)

Hope this helps!

**Comment by sharkck** [comment] 2016-11-30 20:56
Just tried to connect again... Now it's showing the issue with a Shade.  Time to restart the server I suppose!

[crash-2016-11-30_15.55.04-client.txt](https://github.com/Lycanite/LycanitesMobs/files/622957/crash-2016-11-30_15.55.04-client.txt)

**Comment by sharkck** [comment] 2016-11-30 21:01
Upon logging into the server console, I noticed something that may be of interest.  Here is what I found:
![image](https://cloud.githubusercontent.com/assets/960552/20771066/f0bf0676-b715-11e6-84c6-239663591494.png)
The line of interest, after the disconnect says keeping entity shadowmobs.shade that already exists with UUID *******************.  This happened with the shade as well. 

Not sure if this indicative of anything... I'm seeing it with a bunch of abyssalcraft mobs as well.  I'm attaching the logfile and the debug file for the server as well.

[fml-server-latest.txt](https://github.com/Lycanite/LycanitesMobs/files/622977/fml-server-latest.txt)

**Comment by sharkck** [comment] 2016-11-30 21:10
Well restarting the server fixed it (I assume it despawned the bad mobs).

**Comment by sharkck** [comment] 2016-12-01 04:24
Tried to login again, and started crashing again due to this.  Tried to teleport to random locations upon connecting (via tp in server console) and wherever I teleport to, there seems to be a grue or shade where I TP to.  Is this just something to do with a specific aspect of the mod?  Can it be disabled until it's fixed?  I do not know why all of a sudden this is happening.  Things have been from the update until now.

**Comment by Lycanite** [comment] 2016-12-01 08:00
Ah it's the same casting issue from before, I think I know what I missed though so I'll try and get a new update out later today. I'm gonna close this issue and just keep using the casting issue. It's a massive pain really as the bug isn't on Lycanite's Mobs end from what I can find, all I can do is find any case that it could happen and suppress a crash, this also means that sometimes the client will ignore messages from the server but that's better than a crash.

**Closed by Lycanite** 2016-12-01 08:00 UTC

**Comment by sharkck** [comment] 2016-12-06 06:13
Still looking forward to an update.  I've noticed that there have been ~5 updates to Forge recently as well.  I hope all is going well for you and yours!

**Comment by xlxAciDxlx** [comment] 2016-12-06 06:20
If I can figure out how to properly submit a pull request I'll try to fix some of these as I play.

**Comment by Lycanite** [comment] 2016-12-06 08:03
Don't worry, the update is on its way! :D 
And thanks @xlxAciDxlx!

**Comment by sharkck** [comment] 2016-12-07 08:13
I have two more reports to send your way.  I built a Quantum Quarry (Extra Utilities 2) and after abotu 2 minutes, it crashed the server hard with these two crash logs.  It seems linked to Lycanites.  If it's not related to the casting bug, and it is Lycanites related, I hope it helps! 

[crash-2016-12-07_03.05.23-server.txt](https://github.com/Lycanite/LycanitesMobs/files/636029/crash-2016-12-07_03.05.23-server.txt)
[crash-2016-12-07_03.07.40-server.txt](https://github.com/Lycanite/LycanitesMobs/files/636030/crash-2016-12-07_03.07.40-server.txt)

**Comment by Lycanite** [comment] 2016-12-07 08:27
Ah that looks like it might be Extra Utilities 2, my mod is spawning a mob which creates a Forge spawn event, though I'm sure that event can canceled so that's strange, I'll have to ensure that I'm not calling that wrong or something, though it's been fine in the past.
You can stop this crash via the spawning configs by setting ignore spawn events to true, but that will mean that various EU2 blocks, etc that prevent mobs from spawning will no longer be able to prevent mobs from Lycanites Mobs from spawning.

**Comment by Lycanite** [comment] 2016-12-07 08:42
That sounds like it would work. Your best bet is to go through the spawning configs and look each each of the group dimension settings, some are set to blacklists and others are whitelists.

**Comment by sharkck** [comment] 2016-12-07 08:50
Ahh. I only looked in the Lycanitesmobs-spawning.cfg... I see it in each individual spawning config.  I'll try to play with it some tomorrow. It's getting rather late.  I've got the world rolled back now... didn't lose too much.

**Comment by Lycanite** [comment] 2016-12-07 09:00
Ah good! Yeah the configs are split up by group, otherwise there would be one giant config. At some point I'd like to use the Forge config menus, but that could take a while.

**Comment by charlesbevans** [comment] 2016-12-08 16:58
I confirmed the crash rather easily, but I didn't change the 17 configs because the events may need to be disabled as well. EU2 blocks mob spawning in the quarry dimension and events that force spawn vanilla mobs might still cause a crash. The mob blocking code was added in EU 1.0.0, but I was able to run 1.1.0 for several minutes without incident (YMMV). The temporary solution would be to roll back EU until this is resolved.
Is there an interface or something for cancelable events that Lycanite's mobs can handle? Alternatively, a universal blacklist that also blocks events in that dimension *might* be the easiest fix.

**Comment by sharkck** [comment] 2016-12-10 08:37
Also, could you, by chance, implement an admin command to remove/kill all Lycanites mobs?  That could possibly help with the casting issue as well in case there's further issues aside from what you're patching up regarding that casting bug.

**Comment by xlxAciDxlx** [comment] 2016-12-10 14:32
In my opinion it would be better for the issue to be fixed properly. Plus couldn't the vanilla Minecraft command be used for that, or does that only target vanilla entities?

**Comment by sharkck** [comment] 2016-12-11 01:25
I had forgotten about that.... *does /kill @e[type=!Player] .... *Restores backup of world from 20 minutes ago.... DOH!
So... newb question... how would I modify that to just target Lycanites mobs?

**Comment by xlxAciDxlx** [comment] 2016-12-11 02:14
Hmm.. I'm honestly not sure how/if it's possible. I'll do some testing if I can find the time and get back to you.

**Comment by sharkck** [comment] 2016-12-15 02:55
Just checking on the progress on things.  Getting anxious and hope to re-enable most of the mob spawns soon!  By the way, did you want me to open a separate issue for that quarry issue?
