### ISSUE TITLE
[1.7.10 - 1.13.0.5][LAN]Picking up players not happening

### ISSUE THREAD

**Issue by Vascar** [Lycanite/LycanitesMobs#166] opened 2016-07-03 15:23 UTC
While playing a lan game the beast that normal pickup (ex: Roc) players to drop them for falling damage won't. What will happen is the mob that attempted to will quickly fly up about 20 or so blocks and derp out. The player hit by this attack will be unable to interact with chest, items on the ground, and exp orb. Although the exp orbs are still attracted to the player and the player is still able to break blocks as normal. The weirdness ends upon death, or despawn of the player or mob. The despawn is a player logging out or a change to peaceful mode removing the mob in question.

**Comment by Lycanite** [comment] 2016-07-04 07:09
Thanks for posting the bug, I shall take a look into it!

**Comment by cosmo3001** [comment] 2017-03-19 22:24
version 1.11.0.5 is the latest version i can get to work without the bug caused by Roc and other flyers

**Comment by Lycanite** [comment] 2017-08-12 15:22
Should be fixed in 1.16.2.2!
If the problem still happens please open up a new issue.

**Closed by Lycanite** 2017-08-12 15:22 UTC
Labels: bug
